package vectorcomparator;

import javax.swing.*;
import java.text.*;
import java.io.File;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;

//import com.kitfox.svg.*;
//import com.kitfox.svg.app.beans.SVGPanel;

import java.awt.Graphics2D;
import java.awt.image.BufferedImage;

import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author user
 */
public class MainForm extends javax.swing.JFrame {

    String p1;
    String p2;
    
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bObserve = new javax.swing.JButton();
        bObserve2 = new javax.swing.JButton();
        bCalculate = new javax.swing.JButton();
        bExit = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        Path1 = new javax.swing.JTextField();
        Path2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bObserve.setText("Обзор");
        bObserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bObserveActionPerformed(evt);
            }
        });

        bObserve2.setText("Обзор");
        bObserve2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bObserve2ActionPerformed(evt);
            }
        });

        bCalculate.setText("Рассчитать");
        bCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCalculateActionPerformed(evt);
            }
        });

        bExit.setText("Выход");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);

        Path1.setEditable(false);

        Path2.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bExit)
                    .addComponent(bCalculate)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(bObserve)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 295, Short.MAX_VALUE)
                .addComponent(bObserve2)
                .addGap(125, 125, 125))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Path1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Path2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(bExit)
                .addGap(101, 101, 101)
                .addComponent(bCalculate)
                .addGap(40, 40, 40)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Path1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Path2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bObserve)
                    .addComponent(bObserve2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCalculateActionPerformed
        
        jTextField1.setText(String.valueOf(new DecimalFormat("#.##").format(VectorComparator.Compare(p1, p2))));
        
        /*
        JInternalFrame iFrame = new JInternalFrame();
        iFrame.show();
        JButton b = new JButton();
        b.setText(String.valueOf(VectorComparator.Compare(p1, p2)));
        iFrame.add(b);
        */
        
    }//GEN-LAST:event_bCalculateActionPerformed

    private void bObserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bObserveActionPerformed
        FileNameExtensionFilter filter = new FileNameExtensionFilter("SVG Files", "svg");
        
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(filter);
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        p1 = f.getAbsolutePath();
        Path1.setText(p1);
        
        /*
        try{
            BufferedImage pic = ImageIO.read(f);
            JLabel picLabel = new JLabel(new ImageIcon(pic));
            add(picLabel);
        }catch(Exception e){
            System.out.println("exc");
        }
        */
        
        BufferedImage image = new BufferedImage(100, 100, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g = image.createGraphics();
        //g.setClip(jPanel1.getX(), jPanel1.getX(), jPanel1.getHeight(), jPanel1.getWidth());
        /*
        SVGUniverse svgUniverse = new SVGUniverse();
        try{
            svgUniverse.loadSVG(f.toURI().toURL());
                    
            SVGDiagram svgDiagram = svgUniverse.getDiagram(svgUniverse.loadSVG(f.toURI().toURL()));
            svgDiagram.render(g);
            svgDiagram.setIgnoringClipHeuristic(true);
            
            svgUniverse.setCurTime(1);
            svgUniverse.updateTime();
            System.out.println("nope");
        }catch(Exception e){
            System.out.println("catch ya!");
        }
        */
        /*
        SVGPanel svgPanel = new SVGPanel();
        try{
            svgPanel.setSvgResourcePath(p1);
        }catch(Exception e){}
        svgPanel.setVisible(true);
        svgPanel.setLocation(jPanel1.getX(), jPanel1.getY());
        svgPanel.setScaleToFit(true);
        */
    }//GEN-LAST:event_bObserveActionPerformed

    private void bObserve2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bObserve2ActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        p2 = chooser.getSelectedFile().getAbsolutePath();
        Path2.setText(p2);
    }//GEN-LAST:event_bObserve2ActionPerformed

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_bExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Path1;
    private javax.swing.JTextField Path2;
    private javax.swing.JButton bCalculate;
    private javax.swing.JButton bExit;
    private javax.swing.JButton bObserve;
    private javax.swing.JButton bObserve2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
